# Generated by Django 5.1.3 on 2024-12-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
    ]
