# Generated by Django 5.1.3 on 2024-12-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_fin',
        ),
    ]
