# Generated by Django 5.1.3 on 2024-12-05 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_arriendo_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 33, 23, 444370)),
        ),
    ]
