# Generated by Django 5.1.3 on 2024-12-05 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_arriendo_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 48, 43, 268497)),
        ),
        migrations.AddField(
            model_name='availability',
            name='libre',
            field=models.JSONField(default=['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='hora',
            field=models.TimeField(default=datetime.time(0, 48, 43, 268497)),
        ),
    ]
