# Generated by Django 5.1.3 on 2024-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_availability_hora_remove_availability_libre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
